-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQg2bf2lvDxjB4e84/S
TCf0PRpfPw8adRV2wqvNxaSF4MygCgYIKoZIzj0DAQehRANCAAQgEGuRNMLkP2s1
0/OIpKm4uritSIS8WjG9xsWKbbsLjCitxiiKYXdZMublMFKQQIpueRn/26ZZeYoB
IcpZFh5s
-----END PRIVATE KEY-----