# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
 lane :beta do
   sync_code_signing(type: "appstore")    # see code signing guide for more information
   build_app(project: "builds/ios/Unity-iPhone.xcodeproj")
   upload_to_testflight(apple_id: "armankara19@gmail.com", changelog: "Add rocket emoji Test from Circle ci 1")
 end
end
