# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
 lane :beta do
 app_store_connect_api_key(
     key_id: "LQ2NJW67MU",
     issuer_id: "bcc39850-b8b5-4d50-82b1-87a437af958f",
     key_filepath: "fastlane/AuthKey_LQ2NJW67MU.p8",
     duration: 1200, # optional (maximum 1200)
     in_house: false # optional but may be required if using match/sigh
   )
  match(type: "appstore", readonly: true)
  match(type: "development", readonly: true)
  match(type: "adhoc", readonly: true)
  
enable_automatic_code_signing(
  path: "Builds/iOS/UnityBuild/Unity-iPhone.xcodeproj"
)

   build_app(xcargs: "-UseModernBuildSystem=YES" ,export_method: "app-store", project: "Builds/iOS/UnityBuild/Unity-iPhone.xcodeproj")


   PROJECT_APP_ID = "1635039016"
   apple_userid = CredentialsManager::AppfileConfig.try_fetch_value(:apple_id)
    upload_to_testflight(
         username: apple_userid,
         apple_id: PROJECT_APP_ID,
         skip_submission: true,
         skip_waiting_for_build_processing: true
       )
 end
end
